version: '3.8'

services:
  api:
    image: quay.io/go-skynet/local-ai:latest
    container_name: localAI-service
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models
    command: [ "/usr/bin/local-ai" ]

  fastapi:
    build:
      context: fastapi
      dockerfile: Dockerfile
    image: fastapi
    container_name: fastapi
    volumes:
      - ./images/:/workdir/images/
    ports:
      - 9080:9080
    restart: on-failure